spring:
  sql.init:
    schema-locations: classpath:schema.sql
logging.level:
  ru.practicum: TRACE
  org:
    zalando.logbook: TRACE
    springframework.jdbc.core:
      JdbcTemplate: TRACE
      StatementCreatorUtils: TRACE