spring:
  main:
    #log-startup-info: false # выводим служебную информацию
    banner-mode: off       # не выводим баннер
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stats-db
  jpa:
    show-sql: true
logging.level:
  ru.practicum.statistic: TRACE
  org:
    zalando.logbook: TRACE
    springframework.jdbc.core:
      JdbcTemplate: TRACE
      StatementCreatorUtils: TRACE
